class Pessoas {

    static pessoa() {
        return [
            {
                "nome": "Sebastião Levi Brito",
                "idade": 63,
                "cpf": "950.303.322-51",
                "rg": "22.521.787-9",
                "data_nasc": "06/07/1959",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Cristiane Clara",
                "pai": "Tiago Thales Diogo Brito",
                "email": "sebastiao_levi_brito@yoma.com.br",
                "senha": "akD6XW03aL",
                "cep": "88330-360",
                "endereco": "Rua 2870",
                "numero": 891,
                "bairro": "Centro",
                "cidade": "Balneário Camboriú",
                "estado": "SC",
                "telefone_fixo": "(47) 3664-8115",
                "celular": "(47) 99391-8187",
                "altura": "1,96",
                "peso": 91,
                "tipo_sanguineo": "A-",
                "cor": "laranja"
            }, {
                "nome": "Eduardo Cauã Caldeira",
                "idade": 18,
                "cpf": "863.782.001-81",
                "rg": "15.623.173-6",
                "data_nasc": "13/03/2004",
                "sexo": "Masculino",
                "signo": "Peixes",
                "mae": "Sônia Kamilly Alice",
                "pai": "Lorenzo Eduardo Manuel Caldeira",
                "email": "eduardo_caldeira@mktec.com.br",
                "senha": "9tzl5zciML",
                "cep": "77820-378",
                "endereco": "Rua 85",
                "numero": 271,
                "bairro": "Jardim dos Ipês III",
                "cidade": "Araguaína",
                "estado": "TO",
                "telefone_fixo": "(63) 2981-3555",
                "celular": "(63) 99960-3666",
                "altura": "1,75",
                "peso": 73,
                "tipo_sanguineo": "B-",
                "cor": "verde"
            },
            {
                "nome": "Fátima Agatha Oliveira",
                "idade": 18,
                "cpf": "097.459.694-94",
                "rg": "13.432.056-6",
                "data_nasc": "12/04/2004",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Maya Benedita Rosângela",
                "pai": "Yuri Diego César Oliveira",
                "email": "fatima_agatha_oliveira@tetrapark.com",
                "senha": "z8zPCtRAdx",
                "cep": "68902-861",
                "endereco": "Avenida Felipe Camarão",
                "numero": 971,
                "bairro": "Buritizal",
                "cidade": "Macapá",
                "estado": "AP",
                "telefone_fixo": "(96) 3704-6403",
                "celular": "(96) 98350-3367",
                "altura": "1,66",
                "peso": 63,
                "tipo_sanguineo": "AB+",
                "cor": "roxo"
            },

            {
                "nome": "Anthony Felipe Lucca Galvão",
                "idade": 20,
                "cpf": "156.951.459-37",
                "rg": "21.749.059-1",
                "data_nasc": "22/03/2002",
                "sexo": "Masculino",
                "signo": "Áries",
                "mae": "Rita Carolina Vanessa",
                "pai": "Lucas Levi Galvão",
                "email": "anthony_felipe_galvao@muvacademia.com.br",
                "senha": "PM6APAJwoI",
                "cep": "35681-304",
                "endereco": "Rua José Júlio Campanha",
                "numero": 649,
                "bairro": "Santanense",
                "cidade": "Itaúna",
                "estado": "MG",
                "telefone_fixo": "(37) 3631-5628",
                "celular": "(37) 99717-9686",
                "altura": "1,83",
                "peso": 93,
                "tipo_sanguineo": "O+",
                "cor": "amarelo"
            },
            {
                "nome": "Daniel Mateus Francisco Monteiro",
                "idade": 20,
                "cpf": "569.736.874-74",
                "rg": "10.546.351-6",
                "data_nasc": "25/02/2002",
                "sexo": "Masculino",
                "signo": "Peixes",
                "mae": "Francisca Mariane",
                "pai": "Yago Paulo Monteiro",
                "email": "daniel_monteiro@fluxioneventos.com.br",
                "senha": "o4YLPTu2Rd",
                "cep": "69313-715",
                "endereco": "Rua Tenente Braz Barros da Silva",
                "numero": 779,
                "bairro": "Jardim Caranã",
                "cidade": "Boa Vista",
                "estado": "RR",
                "telefone_fixo": "(95) 2716-6202",
                "celular": "(95) 99674-0373",
                "altura": "1,71",
                "peso": 70,
                "tipo_sanguineo": "O-",
                "cor": "verde"
            },
            {
                "nome": "Maitê Ana Souza",
                "idade": 20,
                "cpf": "132.067.250-70",
                "rg": "21.862.051-2",
                "data_nasc": "01/03/2002",
                "sexo": "Feminino",
                "signo": "Peixes",
                "mae": "Bruna Heloisa",
                "pai": "Carlos Raul Sebastião Souza",
                "email": "maite_ana_souza@picolotoengenharia.com.br",
                "senha": "9Pm1SF8qT8",
                "cep": "68745-210",
                "endereco": "Alameda Carlos Gomes",
                "numero": 369,
                "bairro": "Santa Lídia",
                "cidade": "Castanhal",
                "estado": "PA",
                "telefone_fixo": "(91) 2987-3401",
                "celular": "(91) 98582-7053",
                "altura": "1,56",
                "peso": 56,
                "tipo_sanguineo": "O-",
                "cor": "verde"
            },
            {
                "nome": "Igor Victor Assis",
                "idade": 20,
                "cpf": "509.505.909-67",
                "rg": "24.876.215-1",
                "data_nasc": "01/07/2002",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Analu Bárbara",
                "pai": "Oliver Anderson Lucas Assis",
                "email": "igor_victor_assis@distribuidorapetfarm.com.br",
                "senha": "pn9i1kD5fn",
                "cep": "57045-600",
                "endereco": "Rua Santa Luzia",
                "numero": 573,
                "bairro": "Barro Duro",
                "cidade": "Maceió",
                "estado": "AL",
                "telefone_fixo": "(82) 3680-7690",
                "celular": "(82) 99432-8146",
                "altura": "1,81",
                "peso": 96,
                "tipo_sanguineo": "O-",
                "cor": "laranja"
            },
            {
                "nome": "Cláudio Manuel Gabriel Brito",
                "idade": 20,
                "cpf": "860.955.556-98",
                "rg": "29.301.780-3",
                "data_nasc": "03/05/2002",
                "sexo": "Masculino",
                "signo": "Touro",
                "mae": "Betina Juliana Analu",
                "pai": "Pedro Arthur Brito",
                "email": "claudio_brito@eternalam.com.br",
                "senha": "9m6RZbJCgD",
                "cep": "29145-433",
                "endereco": "Rua Raquel de Jesus Ribeiro",
                "numero": 566,
                "bairro": "São Francisco",
                "cidade": "Cariacica",
                "estado": "ES",
                "telefone_fixo": "(27) 2776-7618",
                "celular": "(27) 98797-6344",
                "altura": "1,85",
                "peso": 101,
                "tipo_sanguineo": "A+",
                "cor": "laranja"
            },
            {
                "nome": "Anthony Fábio Porto",
                "idade": 20,
                "cpf": "276.697.193-97",
                "rg": "35.286.455-2",
                "data_nasc": "15/02/2002",
                "sexo": "Masculino",
                "signo": "Aquário",
                "mae": "Caroline Jennifer Sebastiana",
                "pai": "Pedro Henrique Heitor Oliver Porto",
                "email": "anthony.fabio.porto@caesarbusiness.com.br",
                "senha": "NI2fkItUyZ",
                "cep": "55002-072",
                "endereco": "2ª Travessa Jornalista Aníbal Fernandes",
                "numero": 822,
                "bairro": "Nossa Senhora das Dores",
                "cidade": "Caruaru",
                "estado": "PE",
                "telefone_fixo": "(81) 2740-3056",
                "celular": "(81) 98725-0362",
                "altura": "1,93",
                "peso": 58,
                "tipo_sanguineo": "A-",
                "cor": "laranja"
            },
            {
                "nome": "Patrícia Stefany Rodrigues",
                "idade": 20,
                "cpf": "175.803.239-15",
                "rg": "33.624.119-7",
                "data_nasc": "24/02/2002",
                "sexo": "Feminino",
                "signo": "Peixes",
                "mae": "Márcia Teresinha Milena",
                "pai": "Henry Iago Rodrigues",
                "email": "patriciastefanyrodrigues@cincoentretenimentos.com.br",
                "senha": "nPaQX2ZFcQ",
                "cep": "67145-235",
                "endereco": "Quadra Vinte e Um",
                "numero": 936,
                "bairro": "Maguari",
                "cidade": "Ananindeua",
                "estado": "PA",
                "telefone_fixo": "(91) 3777-3974",
                "celular": "(91) 98329-4228",
                "altura": "1,64",
                "peso": 60,
                "tipo_sanguineo": "B-",
                "cor": "laranja"
            },
            {
                "nome": "Sara Alessandra Barros",
                "idade": 18,
                "cpf": "947.252.006-54",
                "rg": "19.733.458-1",
                "data_nasc": "20/02/2004",
                "sexo": "Feminino",
                "signo": "Peixes",
                "mae": "Sophia Vitória",
                "pai": "Guilherme André Marcelo Barros",
                "email": "sara.alessandra.barros@negocios-de-valor.com",
                "senha": "ctmLMpLrcd",
                "cep": "35660-413",
                "endereco": "Rua Bonina",
                "numero": 951,
                "bairro": "Jardim Castelo Branco",
                "cidade": "Pará de Minas",
                "estado": "MG",
                "telefone_fixo": "(37) 3759-4380",
                "celular": "(37) 99704-9524",
                "altura": "1,82",
                "peso": 67,
                "tipo_sanguineo": "B+",
                "cor": "laranja"
            },
            {
                "nome": "Pedro Henrique Matheus Martins",
                "idade": 18,
                "cpf": "657.374.726-71",
                "rg": "42.022.391-5",
                "data_nasc": "09/03/2004",
                "sexo": "Masculino",
                "signo": "Peixes",
                "mae": "Fabiana Sônia Carolina",
                "pai": "Márcio Rodrigo José Martins",
                "email": "pedrohenriquemartins@freitas.net.br",
                "senha": "SolTCI8m3R",
                "cep": "64031-091",
                "endereco": "Rua Quatorze",
                "numero": 481,
                "bairro": "Bela Vista",
                "cidade": "Teresina",
                "estado": "PI",
                "telefone_fixo": "(86) 3999-9790",
                "celular": "(86) 98393-3678",
                "altura": "1,85",
                "peso": 81,
                "tipo_sanguineo": "AB-",
                "cor": "vermelho"
            },
            {
                "nome": "Letícia Rafaela Luciana Novaes",
                "idade": 18,
                "cpf": "456.049.470-32",
                "rg": "25.359.440-6",
                "data_nasc": "16/05/2004",
                "sexo": "Feminino",
                "signo": "Touro",
                "mae": "Amanda Luzia Luzia",
                "pai": "Alexandre Davi Novaes",
                "email": "leticiarafaelanovaes@cbb.com.br",
                "senha": "mJN8l6XLmZ",
                "cep": "72003-015",
                "endereco": "Rua Rua 10 Chácara 183",
                "numero": 451,
                "bairro": "Vila São José (Vicente Pires)",
                "cidade": "Brasília",
                "estado": "DF",
                "telefone_fixo": "(61) 2865-6192",
                "celular": "(61) 99493-7938",
                "altura": "1,75",
                "peso": 48,
                "tipo_sanguineo": "B-",
                "cor": "preto"
            },
            {
                "nome": "Heitor Tomás Felipe Peixoto",
                "idade": 18,
                "cpf": "272.731.956-85",
                "rg": "11.592.134-5",
                "data_nasc": "04/07/2004",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Bárbara Cláudia",
                "pai": "Matheus Isaac Peixoto",
                "email": "heitor-peixoto80@cosma.com",
                "senha": "Cshn183jPk",
                "cep": "58414-600",
                "endereco": "Rua Pedro Silva",
                "numero": 927,
                "bairro": "Tambor",
                "cidade": "Campina Grande",
                "estado": "PB",
                "telefone_fixo": "(83) 3900-9712",
                "celular": "(83) 98286-8625",
                "altura": "1,61",
                "peso": 80,
                "tipo_sanguineo": "B-",
                "cor": "laranja"
            },
            {
                "nome": "Alana Cecília Yasmin Mendes",
                "idade": 18,
                "cpf": "666.551.810-89",
                "rg": "12.084.055-8",
                "data_nasc": "04/04/2004",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Emilly Maria",
                "pai": "Benjamin Jorge Theo Mendes",
                "email": "alana_mendes@unifox.com.br",
                "senha": "NJhSMS545g",
                "cep": "49051-050",
                "endereco": "Rua Professora Maria do Carmo Dias",
                "numero": 600,
                "bairro": "Pereira Lobo",
                "cidade": "Aracaju",
                "estado": "SE",
                "telefone_fixo": "(79) 2853-0954",
                "celular": "(79) 98497-6614",
                "altura": "1,70",
                "peso": 83,
                "tipo_sanguineo": "AB-",
                "cor": "verde"
            },
            {
                "nome": "Bianca Bárbara Jennifer Novaes",
                "idade": 69,
                "cpf": "523.465.340-48",
                "rg": "32.155.880-7",
                "data_nasc": "08/06/1953",
                "sexo": "Feminino",
                "signo": "Gêmeos",
                "mae": "Vera Elaine",
                "pai": "Leonardo Guilherme Tiago Novaes",
                "email": "bianca.barbara.novaes@gmail.com",
                "senha": "o86z1aUFuu",
                "cep": "29222-613",
                "endereco": "Rua Pedro José Luiz",
                "numero": 218,
                "bairro": "Paturá",
                "cidade": "Guarapari",
                "estado": "ES",
                "telefone_fixo": "(27) 3730-1048",
                "celular": "(27) 99431-2014",
                "altura": "1,54",
                "peso": 47,
                "tipo_sanguineo": "A-",
                "cor": "vermelho"
            },
            {
                "nome": "Antonella Antônia Carolina Bernardes",
                "idade": 27,
                "cpf": "750.827.558-62",
                "rg": "44.851.095-9",
                "data_nasc": "13/05/1995",
                "sexo": "Feminino",
                "signo": "Touro",
                "mae": "Cristiane Emanuelly",
                "pai": "Benjamin Osvaldo José Bernardes",
                "email": "antonellaantoniabernardes@mcpsolucoesgraficas.com.br",
                "senha": "fxCW2rDYr2",
                "cep": "78140-282",
                "endereco": "Rua Ébano",
                "numero": 119,
                "bairro": "Glória",
                "cidade": "Várzea Grande",
                "estado": "MT",
                "telefone_fixo": "(65) 3954-5222",
                "celular": "(65) 98998-0662",
                "altura": "1,56",
                "peso": 79,
                "tipo_sanguineo": "A-",
                "cor": "roxo"
            },
            {
                "nome": "Ian Danilo Iago da Conceição",
                "idade": 32,
                "cpf": "795.163.818-80",
                "rg": "13.911.266-2",
                "data_nasc": "01/07/1990",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Rita Brenda Louise",
                "pai": "André Eduardo da Conceição",
                "email": "ian_daconceicao@gmeil.com",
                "senha": "1EswUKiSqu",
                "cep": "67125-286",
                "endereco": "Passagem Onze de Agosto",
                "numero": 135,
                "bairro": "Icuí-Guajará",
                "cidade": "Ananindeua",
                "estado": "PA",
                "telefone_fixo": "(91) 2702-4806",
                "celular": "(91) 99128-0786",
                "altura": "1,84",
                "peso": 51,
                "tipo_sanguineo": "A-",
                "cor": "laranja"
            },
            {
                "nome": "Clarice Vanessa Bruna Figueiredo",
                "idade": 68,
                "cpf": "136.142.230-00",
                "rg": "23.804.706-4",
                "data_nasc": "01/02/1954",
                "sexo": "Feminino",
                "signo": "Aquário",
                "mae": "Yasmin Raquel",
                "pai": "Pedro Henrique Samuel Figueiredo",
                "email": "clarice_vanessa_figueiredo@iblojas.com.br",
                "senha": "PpMDXFKwtQ",
                "cep": "68909-080",
                "endereco": "Rua Guilherme Coelho",
                "numero": 175,
                "bairro": "Jardim Felicidade",
                "cidade": "Macapá",
                "estado": "AP",
                "telefone_fixo": "(96) 3609-2068",
                "celular": "(96) 98643-3818",
                "altura": "1,74",
                "peso": 52,
                "tipo_sanguineo": "AB+",
                "cor": "laranja"
            },
            {
                "nome": "Benedito Augusto Aparício",
                "idade": 36,
                "cpf": "167.275.907-29",
                "rg": "40.901.558-1",
                "data_nasc": "12/03/1986",
                "sexo": "Masculino",
                "signo": "Peixes",
                "mae": "Maria Antônia",
                "pai": "Fernando Henrique Danilo Aparício",
                "email": "benedito_aparicio@brastek.com.br",
                "senha": "JaqD8FJl2W",
                "cep": "65917-642",
                "endereco": "Avenida Araguaia",
                "numero": 358,
                "bairro": "Parque das Mansões",
                "cidade": "Imperatriz",
                "estado": "MA",
                "telefone_fixo": "(98) 3739-9303",
                "celular": "(98) 99146-3119",
                "altura": "1,84",
                "peso": 80,
                "tipo_sanguineo": "B-",
                "cor": "verde"
            },
            {
                "nome": "Márcio Victor Vinicius Farias",
                "idade": 62,
                "cpf": "643.237.680-79",
                "rg": "16.674.393-8",
                "data_nasc": "01/07/1960",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Benedita Aline",
                "pai": "Erick Enrico Farias",
                "email": "marcio_victor_farias@jammer.com.br",
                "senha": "csuIG7xlTC",
                "cep": "85871-028",
                "endereco": "Rua Bento Coelho",
                "numero": 111,
                "bairro": "Loteamento Porto Dourado",
                "cidade": "Foz do Iguaçu",
                "estado": "PR",
                "telefone_fixo": "(45) 2532-6525",
                "celular": "(45) 99702-5205",
                "altura": "1,60",
                "peso": 95,
                "tipo_sanguineo": "O+",
                "cor": "amarelo"
            },
            {
                "nome": "Sérgio Erick Henrique Gomes",
                "idade": 29,
                "cpf": "809.662.753-81",
                "rg": "19.740.901-5",
                "data_nasc": "20/05/1993",
                "sexo": "Masculino",
                "signo": "Touro",
                "mae": "Isabelle Giovanna",
                "pai": "Raimundo Enzo Gomes",
                "email": "sergio_erick_gomes@ritmolog.com.br",
                "senha": "4Eho8gg9dL",
                "cep": "77023-573",
                "endereco": "Quadra 1006 Sul Alameda 16",
                "numero": 323,
                "bairro": "Plano Diretor Sul",
                "cidade": "Palmas",
                "estado": "TO",
                "telefone_fixo": "(63) 2632-1825",
                "celular": "(63) 99657-6682",
                "altura": "1,86",
                "peso": 60,
                "tipo_sanguineo": "A-",
                "cor": "vermelho"
            },
            {
                "nome": "Antônia Luciana da Rosa",
                "idade": 49,
                "cpf": "907.457.973-69",
                "rg": "37.422.413-4",
                "data_nasc": "04/04/1973",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Fátima Carolina",
                "pai": "Marcos Vinicius Vicente Ian da Rosa",
                "email": "antonia_darosa@viavaleseguros.com.br",
                "senha": "Aa6a0qY4a2",
                "cep": "49045-280",
                "endereco": "Avenida Gonçalo Rolemberg Leite",
                "numero": 423,
                "bairro": "Luzia",
                "cidade": "Aracaju",
                "estado": "SE",
                "telefone_fixo": "(79) 3847-0015",
                "celular": "(79) 99440-4892",
                "altura": "1,78",
                "peso": 84,
                "tipo_sanguineo": "B+",
                "cor": "preto"
            },
            {
                "nome": "Isis Heloisa Beatriz Nascimento",
                "idade": 72,
                "cpf": "169.554.636-91",
                "rg": "16.442.288-2",
                "data_nasc": "23/03/1950",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Aparecida Renata Valentina",
                "pai": "Nelson Alexandre Ian Nascimento",
                "email": "isis-nascimento84@emayl.com",
                "senha": "34fULfd2ZC",
                "cep": "19061-420",
                "endereco": "Rua José Afonso",
                "numero": 185,
                "bairro": "Jardim Esplanada",
                "cidade": "Presidente Prudente",
                "estado": "SP",
                "telefone_fixo": "(18) 2960-0604",
                "celular": "(18) 98811-6403",
                "altura": "1,80",
                "peso": 55,
                "tipo_sanguineo": "O+",
                "cor": "amarelo"
            },
            {
                "nome": "Fernando Severino Pedro Henrique Cavalcanti",
                "idade": 34,
                "cpf": "331.479.154-25",
                "rg": "19.910.454-2",
                "data_nasc": "25/01/1988",
                "sexo": "Masculino",
                "signo": "Aquário",
                "mae": "Daniela Andreia",
                "pai": "Márcio Murilo Cavalcanti",
                "email": "fernando-cavalcanti87@doucedoce.com.br",
                "senha": "ZjDTCxrW5J",
                "cep": "72546-613",
                "endereco": "Quadra QR 316 Conjunto M",
                "numero": 688,
                "bairro": "Santa Maria",
                "cidade": "Brasília",
                "estado": "DF",
                "telefone_fixo": "(61) 2569-8598",
                "celular": "(61) 99719-1838",
                "altura": "1,74",
                "peso": 91,
                "tipo_sanguineo": "AB+",
                "cor": "verde"
            },
            {
                "nome": "Carlos Eduardo Yuri Pires",
                "idade": 44,
                "cpf": "112.886.807-59",
                "rg": "35.051.836-1",
                "data_nasc": "05/06/1978",
                "sexo": "Masculino",
                "signo": "Gêmeos",
                "mae": "Gabriela Giovana Helena",
                "pai": "Diego Levi Rafael Pires",
                "email": "carlos_eduardo_pires@csjsistemas.com.br",
                "senha": "08F3zS98i2",
                "cep": "86706-630",
                "endereco": "Rua Andarilho",
                "numero": 228,
                "bairro": "Conjunto Ulisses Guimarães",
                "cidade": "Arapongas",
                "estado": "PR",
                "telefone_fixo": "(43) 3631-7011",
                "celular": "(43) 99859-1654",
                "altura": "1,72",
                "peso": 85,
                "tipo_sanguineo": "O-",
                "cor": "amarelo"
            },
            {
                "nome": "Eloá Carolina Jennifer Peixoto",
                "idade": 24,
                "cpf": "590.189.357-35",
                "rg": "20.272.988-6",
                "data_nasc": "04/07/1998",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Letícia Rosângela",
                "pai": "Márcio Ian Peixoto",
                "email": "eloa_peixoto@fulltransport.com.br",
                "senha": "jKg1JlbIoj",
                "cep": "26171-400",
                "endereco": "Travessa dos Cravos",
                "numero": 427,
                "bairro": "Parque Floresta",
                "cidade": "Belford Roxo",
                "estado": "RJ",
                "telefone_fixo": "(21) 2903-4051",
                "celular": "(21) 98378-9402",
                "altura": "1,59",
                "peso": 57,
                "tipo_sanguineo": "AB+",
                "cor": "vermelho"
            },
            {
                "nome": "Manuela Laura Alves",
                "idade": 35,
                "cpf": "077.618.278-18",
                "rg": "26.482.859-8",
                "data_nasc": "03/07/1987",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Tânia Fabiana",
                "pai": "Leonardo Edson Filipe Alves",
                "email": "manuela_laura_alves@br.gestant.com",
                "senha": "ZMG3Ep3xae",
                "cep": "59073-335",
                "endereco": "Rua Santo Expedito",
                "numero": 298,
                "bairro": "Planalto",
                "cidade": "Natal",
                "estado": "RN",
                "telefone_fixo": "(84) 3841-6940",
                "celular": "(84) 99890-3197",
                "altura": "1,61",
                "peso": 84,
                "tipo_sanguineo": "AB-",
                "cor": "preto"
            },
            {
                "nome": "Marlene Camila Barros",
                "idade": 47,
                "cpf": "479.353.846-06",
                "rg": "16.555.675-4",
                "data_nasc": "12/03/1975",
                "sexo": "Feminino",
                "signo": "Peixes",
                "mae": "Bianca Louise",
                "pai": "Thales Leandro Enrico Barros",
                "email": "marlene_barros@aspxsistemas.com.com.br",
                "senha": "bazAFFb0Dw",
                "cep": "54420-750",
                "endereco": "Rua Rio Capim",
                "numero": 323,
                "bairro": "Piedade",
                "cidade": "Jaboatão dos Guararapes",
                "estado": "PE",
                "telefone_fixo": "(81) 3581-4483",
                "celular": "(81) 99134-1296",
                "altura": "1,66",
                "peso": 69,
                "tipo_sanguineo": "O+",
                "cor": "laranja"
            },
            {
                "nome": "Allana Flávia Monteiro",
                "idade": 68,
                "cpf": "831.211.056-98",
                "rg": "18.837.230-1",
                "data_nasc": "07/07/1954",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Raimunda Analu",
                "pai": "Thiago Severino Monteiro",
                "email": "allana_flavia_monteiro@yhaoo.com.br",
                "senha": "HHi7WkxqrE",
                "cep": "13419-144",
                "endereco": "Travessa João Guerra",
                "numero": 885,
                "bairro": "Alto",
                "cidade": "Piracicaba",
                "estado": "SP",
                "telefone_fixo": "(19) 3778-4618",
                "celular": "(19) 98564-8733",
                "altura": "1,69",
                "peso": 83,
                "tipo_sanguineo": "B-",
                "cor": "vermelho"
            },
            {
                "nome": "Vanessa Mirella Ribeiro",
                "idade": 50,
                "cpf": "952.539.248-17",
                "rg": "41.423.629-4",
                "data_nasc": "01/04/1972",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Ester Isabelly Luana",
                "pai": "Ricardo Martin Ribeiro",
                "email": "vanessa_ribeiro@hersa.com.br",
                "senha": "E34egydGDD",
                "cep": "68905-222",
                "endereco": "Rua Raul Clemente Paulo Callins",
                "numero": 182,
                "bairro": "Cidade Nova",
                "cidade": "Macapá",
                "estado": "AP",
                "telefone_fixo": "(96) 2726-3189",
                "celular": "(96) 98775-7031",
                "altura": "1,65",
                "peso": 81,
                "tipo_sanguineo": "O-",
                "cor": "verde"
            },
            {
                "nome": "Elza Isabella Adriana Santos",
                "idade": 54,
                "cpf": "351.466.495-10",
                "rg": "31.594.083-9",
                "data_nasc": "13/04/1968",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Rosa Heloisa",
                "pai": "Murilo Augusto Santos",
                "email": "elza-santos90@band.com.br",
                "senha": "3MpeRr311U",
                "cep": "31530-592",
                "endereco": "Rua Um Mil Quatrocentos e Quarenta e Seis",
                "numero": 893,
                "bairro": "Rio Branco",
                "cidade": "Belo Horizonte",
                "estado": "MG",
                "telefone_fixo": "(31) 2704-7868",
                "celular": "(31) 99361-5261",
                "altura": "1,68",
                "peso": 70,
                "tipo_sanguineo": "B-",
                "cor": "preto"
            },
            {
                "nome": "Juan Hugo Joaquim da Cruz",
                "idade": 30,
                "cpf": "765.653.908-51",
                "rg": "14.274.395-1",
                "data_nasc": "21/05/1992",
                "sexo": "Masculino",
                "signo": "Gêmeos",
                "mae": "Tatiane Luana Luciana",
                "pai": "Anthony Renan Geraldo da Cruz",
                "email": "juan_hugo_dacruz@tecsysbrasil.com.br",
                "senha": "KBFca2NGY2",
                "cep": "69400-098",
                "endereco": "Rua Abel",
                "numero": 683,
                "bairro": "Biribiri",
                "cidade": "Manacapuru",
                "estado": "AM",
                "telefone_fixo": "(92) 3789-4941",
                "celular": "(92) 99662-0889",
                "altura": "1,99",
                "peso": 85,
                "tipo_sanguineo": "AB-",
                "cor": "preto"
            },
            {
                "nome": "Benício Cláudio Kauê Dias",
                "idade": 34,
                "cpf": "597.974.760-57",
                "rg": "20.681.709-5",
                "data_nasc": "03/03/1988",
                "sexo": "Masculino",
                "signo": "Peixes",
                "mae": "Carolina Allana",
                "pai": "Osvaldo Fernando Dias",
                "email": "benicio.claudio.dias@hidrara.com.br",
                "senha": "w6Mco3Bkp8",
                "cep": "79080-290",
                "endereco": "Rua Sol Nascente",
                "numero": 112,
                "bairro": "Jardim Jóquei Club",
                "cidade": "Campo Grande",
                "estado": "MS",
                "telefone_fixo": "(67) 2617-9619",
                "celular": "(67) 98356-6169",
                "altura": "1,69",
                "peso": 54,
                "tipo_sanguineo": "A+",
                "cor": "amarelo"
            },
            {
                "nome": "Laís Lúcia da Mota",
                "idade": 77,
                "cpf": "012.828.512-50",
                "rg": "36.802.728-4",
                "data_nasc": "06/07/1945",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Clara Camila",
                "pai": "Igor Giovanni da Mota",
                "email": "laisluciadamota@yahoo.ca",
                "senha": "hyIUhtUs9O",
                "cep": "57073-270",
                "endereco": "Rua Waldemar Costa Oliveira",
                "numero": 928,
                "bairro": "Cidade Universitária",
                "cidade": "Maceió",
                "estado": "AL",
                "telefone_fixo": "(82) 3928-8616",
                "celular": "(82) 99240-5684",
                "altura": "1,84",
                "peso": 80,
                "tipo_sanguineo": "A+",
                "cor": "preto"
            },
            {
                "nome": "Aline Jennifer Oliveira",
                "idade": 54,
                "cpf": "840.688.607-26",
                "rg": "40.732.122-6",
                "data_nasc": "05/07/1968",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Luciana Nair",
                "pai": "Ian Elias Oliveira",
                "email": "aline_jennifer_oliveira@band.com",
                "senha": "JgK3ntuGzY",
                "cep": "59110-030",
                "endereco": "Rua Paulo Lopes",
                "numero": 176,
                "bairro": "Potengi",
                "cidade": "Natal",
                "estado": "RN",
                "telefone_fixo": "(84) 2985-3887",
                "celular": "(84) 99720-5994",
                "altura": "1,81",
                "peso": 86,
                "tipo_sanguineo": "O-",
                "cor": "vermelho"
            },
            {
                "nome": "Andreia Giovanna Eliane Rocha",
                "idade": 62,
                "cpf": "084.802.299-85",
                "rg": "31.208.238-1",
                "data_nasc": "01/07/1960",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Isis Cláudia",
                "pai": "Jorge Lorenzo Rocha",
                "email": "andreia_rocha@hydropowermc.com.br",
                "senha": "E1qRFYY80O",
                "cep": "72710-126",
                "endereco": "Quadra Quadra 12 Rua F",
                "numero": 922,
                "bairro": "Setor Norte (Brazlândia)",
                "cidade": "Brasília",
                "estado": "DF",
                "telefone_fixo": "(61) 2937-7579",
                "celular": "(61) 99583-0011",
                "altura": "1,53",
                "peso": 80,
                "tipo_sanguineo": "O-",
                "cor": "roxo"
            },
            {
                "nome": "Marcelo Tiago Juan Barbosa",
                "idade": 23,
                "cpf": "800.208.599-02",
                "rg": "48.589.943-7",
                "data_nasc": "11/06/1999",
                "sexo": "Masculino",
                "signo": "Gêmeos",
                "mae": "Eliane Marcela",
                "pai": "Lucca Pedro Barbosa",
                "email": "marcelo.tiago.barbosa@br.nestle.com",
                "senha": "212cyeU0gl",
                "cep": "78076-306",
                "endereco": "Rua Quatro",
                "numero": 706,
                "bairro": "Residencial Claúdio Marchetti",
                "cidade": "Cuiabá",
                "estado": "MT",
                "telefone_fixo": "(65) 2997-7323",
                "celular": "(65) 98588-1379",
                "altura": "1,91",
                "peso": 107,
                "tipo_sanguineo": "O+",
                "cor": "vermelho"
            },
            {
                "nome": "Breno Thiago Mateus Fernandes",
                "idade": 49,
                "cpf": "310.695.289-00",
                "rg": "38.888.352-2",
                "data_nasc": "07/07/1973",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Jaqueline Antonella Bianca",
                "pai": "Lucas Victor Fernandes",
                "email": "breno_fernandes@marquesalcantra.comabdv.com.br",
                "senha": "QepK0Of9SM",
                "cep": "59012-550",
                "endereco": "Rua João Virgílio de Miranda",
                "numero": 908,
                "bairro": "Petrópolis",
                "cidade": "Natal",
                "estado": "RN",
                "telefone_fixo": "(84) 2835-3648",
                "celular": "(84) 98662-2299",
                "altura": "1,91",
                "peso": 94,
                "tipo_sanguineo": "O+",
                "cor": "roxo"
            },
            {
                "nome": "Rosângela Isabelle Caldeira",
                "idade": 48,
                "cpf": "086.589.778-62",
                "rg": "39.855.971-5",
                "data_nasc": "12/04/1974",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Rafaela Carla",
                "pai": "Erick Vicente Eduardo Caldeira",
                "email": "rosangela.isabelle.caldeira@directnet.com.br",
                "senha": "g6bX50Zsd6",
                "cep": "65074-380",
                "endereco": "Rua do Arame",
                "numero": 662,
                "bairro": "Vinhais",
                "cidade": "São Luís",
                "estado": "MA",
                "telefone_fixo": "(98) 2761-0859",
                "celular": "(98) 99569-9947",
                "altura": "1,76",
                "peso": 67,
                "tipo_sanguineo": "B+",
                "cor": "amarelo"
            },
            {
                "nome": "Flávia Isabela Tânia Almada",
                "idade": 69,
                "cpf": "918.657.104-40",
                "rg": "11.989.257-1",
                "data_nasc": "03/07/1953",
                "sexo": "Feminino",
                "signo": "Câncer",
                "mae": "Luciana Laura Regina",
                "pai": "Enrico Filipe Severino Almada",
                "email": "flavia_almada@jsagromecanica.com.br",
                "senha": "OAZOQyIXlw",
                "cep": "65081-687",
                "endereco": "Beco da Bíblia",
                "numero": 500,
                "bairro": "Vila Embratel",
                "cidade": "São Luís",
                "estado": "MA",
                "telefone_fixo": "(98) 3634-1340",
                "celular": "(98) 98361-8223",
                "altura": "1,68",
                "peso": 49,
                "tipo_sanguineo": "O-",
                "cor": "vermelho"
            },
            {
                "nome": "Lavínia Tatiane Clara Vieira",
                "idade": 50,
                "cpf": "085.764.064-03",
                "rg": "46.278.749-7",
                "data_nasc": "19/05/1972",
                "sexo": "Feminino",
                "signo": "Touro",
                "mae": "Fabiana Sônia",
                "pai": "Daniel Leandro Alexandre Vieira",
                "email": "laviniatatianevieira@wredenborg.se",
                "senha": "QXgiHpnAMU",
                "cep": "45057-138",
                "endereco": "Rua 8",
                "numero": 848,
                "bairro": "Ayrton Senna",
                "cidade": "Vitória da Conquista",
                "estado": "BA",
                "telefone_fixo": "(77) 3560-9052",
                "celular": "(77) 99195-7486",
                "altura": "1,81",
                "peso": 57,
                "tipo_sanguineo": "B+",
                "cor": "roxo"
            },
            {
                "nome": "Bárbara Alícia Martins",
                "idade": 71,
                "cpf": "537.804.235-61",
                "rg": "44.858.347-1",
                "data_nasc": "05/04/1951",
                "sexo": "Feminino",
                "signo": "Áries",
                "mae": "Analu Carolina Emanuelly",
                "pai": "Rodrigo Pedro Otávio Martins",
                "email": "barbara_martins@mundivox.com.br",
                "senha": "3ubtF7OcrF",
                "cep": "64053-180",
                "endereco": "Avenida Doutor Aquiles Wall Ferraz",
                "numero": 908,
                "bairro": "Santa Isabel",
                "cidade": "Teresina",
                "estado": "PI",
                "telefone_fixo": "(86) 3948-2269",
                "celular": "(86) 99656-2555",
                "altura": "1,74",
                "peso": 90,
                "tipo_sanguineo": "O-",
                "cor": "verde"
            },
            {
                "nome": "Pedro Eduardo Heitor Pereira",
                "idade": 25,
                "cpf": "968.919.307-40",
                "rg": "16.668.217-2",
                "data_nasc": "01/07/1997",
                "sexo": "Masculino",
                "signo": "Câncer",
                "mae": "Valentina Benedita Marcela",
                "pai": "Thiago André Pereira",
                "email": "pedro-pereira97@contabilidadevictoria.com.br",
                "senha": "FzHuCPpsFp",
                "cep": "90119-900",
                "endereco": "Avenida Borges de Medeiros 1501",
                "numero": 348,
                "bairro": "Praia de Belas",
                "cidade": "Porto Alegre",
                "estado": "RS",
                "telefone_fixo": "(51) 2998-7316",
                "celular": "(51) 99113-2179",
                "altura": "1,74",
                "peso": 52,
                "tipo_sanguineo": "A+",
                "cor": "vermelho"
            }
        ];
    }


    static getPessoas = () => {
        return this.lista_pessoas;
    }
}


